//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServiceReader.QuoteWebService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="QuoteWebService.IQuoteWebService")]
    public interface IQuoteWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteWebService/RandomQuote", ReplyAction="http://tempuri.org/IQuoteWebService/RandomQuoteResponse")]
        string RandomQuote();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IQuoteWebService/RandomQuote", ReplyAction="http://tempuri.org/IQuoteWebService/RandomQuoteResponse")]
        System.Threading.Tasks.Task<string> RandomQuoteAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IQuoteWebServiceChannel : WebServiceReader.QuoteWebService.IQuoteWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class QuoteWebServiceClient : System.ServiceModel.ClientBase<WebServiceReader.QuoteWebService.IQuoteWebService>, WebServiceReader.QuoteWebService.IQuoteWebService {
        
        public QuoteWebServiceClient() {
        }
        
        public QuoteWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public QuoteWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public QuoteWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string RandomQuote() {
            return base.Channel.RandomQuote();
        }
        
        public System.Threading.Tasks.Task<string> RandomQuoteAsync() {
            return base.Channel.RandomQuoteAsync();
        }
    }
}
